version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: qlhs_user
      POSTGRES_PASSWORD: StrongPass123
      POSTGRES_DB: qlhs_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://qlhs_user:StrongPass123@db:5432/qlhs_db
      PORT: 4000
    depends_on:
      - db
    volumes:
      - ./backend/templates:/usr/src/app/templates
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  dbdata:
